# Generated by Django 5.2.7 on 2026-07-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='products/')),
                ('title', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=20)),
                ('category', models.CharField(choices=[('sport_shoes', 'Sport Shoes'), ('casual_shoes', 'Casual Shoes'), ('formal_shoes', 'Formal Shoes'), ('slider', 'Slider'), ('bag', 'Bag'), ('belt', 'Belt'), ('watch', 'Watch'), ('sunglasses', 'Sunglasses')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
